name: First Workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-laltest
    steps:
      - name: print greeting
        run: echo "Hello world!"        
      - name: print goodbye
        run: echo "Done - bye!"  
